// src/components/ToggleSwitch/ToggleSwitch.vue
<template>
  <div
    class="flex justify-between items-center cursor-pointer body-2"
    @click="toggle"
  >
    <div class="opacity-40">{{ label }}</div>
    <div
      :class="[
        'w-12',
        'h-6',
        'flex',
        'items-center',
        { 'bg-design-theme': active },
        { 'bg-blue-gray-200': !active },
        'rounded-full',
        'p-1',
        'duration-300',
        'ease-in-out'
      ]"
    >
      <div
        :class="[
          'bg-design-6',
          'w-4',
          'h-4',
          'rounded-full',
          'shadow-md',
          'transform',
          'duration-300',
          'ease-in-out',
          { 'translate-x-6': active }
        ]"
      ></div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'

import { useVModel } from '@vueuse/core'

export default defineComponent({
  name: 'ToggleSwitch',
  props: {
    active: {
      type: Boolean,
      default: false
    },
    label: {
      type: String,
      default: null
    }
  },
  setup(props, { emit }) {
    const active = useVModel(props, 'active', emit)

    const toggle = () => {
      active.value = !active.value
    }

    return {
      toggle
    }
  }
})
</script>

// src/components/ToggleSwitch/ToggleSwitch.tsx
import React from 'react'
import { motion } from 'framer-motion'

interface ToggleSwitchProps {
  label: string
  active: boolean
  onChange: (_active: boolean) => void
}

export const ToggleSwitch: React.FC<ToggleSwitchProps> = ({
  label,
  active,
  onChange,
}) => {
  const handleToggle = () => {
    onChange(!active)
  }

  return (
    <div
      className="flex justify-between items-center font-medium text-sm cursor-pointer"
      onClick={handleToggle}
      data-testid={`toggle-${label.replace(/\s+/g, '-').toLowerCase()}`}
    >
      <div className="text-gray-700 dark:text-gray-300">{label}</div>

      <div
        className={`
          w-12 h-6 flex items-center rounded-full p-1 duration-300 ease-in-out
          ${active ? 'bg-theme-color' : 'bg-gray-300 dark:bg-gray-600'}
        `}
      >
        <motion.div
          className="bg-white shadow-md rounded-full w-4 h-4"
          initial={false}
          animate={{
            x: active ? 24 : 0,
          }}
          transition={{
            type: 'spring',
            stiffness: 500,
            damping: 30,
          }}
        />
      </div>
    </div>
  )
}

export default ToggleSwitch
