// src/components/CheckBox/CheckBox.tsx
import React, { useId } from 'react'
import { motion } from 'framer-motion'
import { FaCheck } from 'react-icons/fa'

interface CheckBoxProps {
  label: string
  checked: boolean
  onChange: (_checked: boolean) => void
}

export const CheckBox: React.FC<CheckBoxProps> = ({
  label,
  checked,
  onChange,
}) => {
  const id = useId()

  const handleToggle = () => {
    onChange(!checked)
  }

  return (
    <div
      className="flex justify-between items-center font-medium text-sm cursor-pointer"
      onClick={handleToggle}
      data-testid={`checkbox-${label.replace(/\s+/g, '-').toLowerCase()}`}
    >
      <label htmlFor={id} className="text-gray-700 dark:text-gray-300">
        {label}
      </label>

      <div className="relative flex items-center w-12 h-6">
        <input
          id={id}
          type="checkbox"
          checked={checked}
          onChange={handleToggle}
          className="absolute opacity-0 w-0 h-0 cursor-pointer"
        />
        <motion.div
          className={`
            absolute flex justify-center items-center w-6 h-6 rounded-full 
            ${checked ? 'bg-theme-color' : 'bg-gray-300 dark:bg-gray-600'}
          `}
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
          transition={{ duration: 0.2 }}
        >
          {checked && (
            <motion.div
              initial={{ scale: 0, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0, opacity: 0 }}
              transition={{ duration: 0.2 }}
            >
              <FaCheck className="text-white text-xs" />
            </motion.div>
          )}
        </motion.div>
      </div>
    </div>
  )
}

export default CheckBox

// src/components/CheckBox/CheckBox.vue
<template>
  <div
    class="flex justify-between items-center cursor-pointer body-2"
    @click="toggle"
  >
    <div :for="id" class="opacity-40">{{ label }}</div>

    <div class="relative w-12 h-25px flex items-center">
      <input
        :id="id"
        v-model="tempChecked"
        type="checkbox"
        class="absolute opacity-0 cursor-pointer w-0 h-0"
      />
      <span
        :class="[
          'absolute',
          'flex',
          'justify-center',
          'items-center',
          'top-0',
          'left-0',
          'h-25px',
          'w-25px',
          'rounded-full',
          { 'bg-design-theme': tempChecked },
          { checked: tempChecked },
          { 'bg-blue-gray-200': !tempChecked }
        ]"
      >
        <img
          v-if="tempChecked"
          src="@/assets/check-mark.svg"
          alt="selected"
          class="w-14px"
        />
      </span>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue'

import { useVModel } from '@vueuse/core'

import uniqid from 'uniqid'

export default defineComponent({
  name: 'CheckBox',
  props: {
    label: {
      type: String,
      default: null
    },
    checked: {
      type: Boolean,
      default: false
    }
  },
  setup(props, { emit }) {
    const id = ref(uniqid())
    const tempChecked = useVModel(props, 'checked', emit)

    const toggle = () => {
      tempChecked.value = !tempChecked.value
    }

    return {
      id,
      tempChecked,

      toggle
    }
  }
})
</script>

<style></style>
